[package]
name = "influx_db_client"
version = "0.7.0"
authors = ["piaoliu <441594700@qq.com>"]
documentation = "https://docs.rs/influx_db_client/"
repository = "https://github.com/driftluo/InfluxDBClient-rs"
description = "InfluxDB Rust driver"
readme = "README.md"
keywords = ["influxdb"]
categories = ["database"]
license = "MIT"
include = ["Cargo.toml", "src/*.rs", "README.md", "LICENSE"]
edition = "2024"
rust-version = "1.85"

[badges]
travis-ci = { repository = "driftluo/InfluxDBClient-rs" }

[dependencies]
reqwest = { version = "^0.13.2", optional = true, default-features = false, features = [
    "json",
    "stream",
] }
serde_json = '^1.0.2'
serde = { version = "^1.0.15", features = ["derive"] }
bytes = "^1"
futures = "^0.3"
url = "^2.5"

[dev-dependencies]
tempdir = "0.3"
tokio = { version = "1", features = ["full"] }


[features]
default = ["reqwest", "reqwest/default-tls"]
reqwest = ["dep:reqwest"]


# Explicit native-tls backend.
native-tls = ["reqwest", "reqwest/native-tls"]
native-tls-vendored = ["reqwest", "reqwest/native-tls-vendored"]
native-tls-no-alpn = ["reqwest", "reqwest/native-tls-no-alpn"]
